<!DOCTYPE html>
<html lang="en">

<head>
    <title>Online Collaboration</title>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <style>
    .container {
        padding: 25px;
    }

    .form-height {
        height: 500px !important;
    }

    .btn {
        width: 100%;
    }
    </style>
</head>

<body>
    <div class="container">
        <form action="/collaboration/collaborate" method="post">
            <div class="form-group">
                <div class="input-group mb-3">
                    <div class="input-group">
                        <input type="text" class="form-control" aria-label="Text input"
                            value="<?php if(isset($date)) echo $date ?> | <?php if(isset($ip)) echo $ip ?>" readonly>
                        <div class="input-group-append">
                            <button class="btn btn-outline-primary dropdown-toggle" type="button" data-toggle="dropdown"
                                aria-haspopup="true" aria-expanded="false">Users</button>
                            <div class="dropdown-menu">
                                <?php foreach($data as $submit) { ?>
                                <a class="dropdown-item" href="?id=<?= $submit->id ?>"><?= $submit->ip ?>
                                    <strong>|</strong>
                                    <?= $submit->date ?></a>
                                <?php } ?>
                            </div>
                        </div>
                    </div>

                    <div class="input-group">
                        <textarea name="content" class="form-control form-height"
                            aria-label="content"><?php if(isset($content)) echo $content ?></textarea>
                    </div>
                </div>
                <button type="submit" class="btn btn-primary">Save</button>
            </div>
        </form>

</body>

</html>